import commands.*;
import enums.*;
import exceptions.SpacesuitsAreOutException;
import objects.Hours;
import objects.ObjectInfo;
import objects.humans.*;
import objects.humans.astronauts.*;
import objects.things.*;

import java.lang.reflect.InvocationTargetException;

public class Main {
    public static void main(String[] args) throws InvocationTargetException, NoSuchMethodException, IllegalAccessException, SpacesuitsAreOutException {
        // creating crew
        Znaika znaika = new Znaika("Знайка");
        DoctorPilulkin doctor = new DoctorPilulkin("Доктор Пилюлькин");
        Fuksia fuksia = new Fuksia("Фуксию");
        KantikAndKvantik kantikAndKvantik = new KantikAndKvantik("Кантик и Квантик");
        Neznaika neznaika = new Neznaika("Незнайка");
        ProfessorZvyozdochkin professor = new ProfessorZvyozdochkin("Профессора Звёздочкина");
        Seledochka seledochka = new Seledochka("Селёдочку");
        VintikAndShpuntik vintikAndShpuntik = new VintikAndShpuntik("Винтик и Шпунтик");
        Astronauts astronauts = new Astronauts("космонавты", znaika, doctor, fuksia, kantikAndKvantik, professor, seledochka, vintikAndShpuntik);

        // creating side characters
        Lunarians lunarians = new Lunarians("Лунатики");
        Kozlik kozlik = new Kozlik("Козлик");

        // creating equipment
        SpacesuitBox box = new SpacesuitBox(new Spacesuit(),
                new Spacesuit(),
                new Spacesuit(),
                new Spacesuit(),
                new Spacesuit(),
                new Spacesuit(),
                new Spacesuit(),
                new Spacesuit());
        Alpenstocks alpenstocks = new Alpenstocks("альпенштоки");
        GeoHammers geoHammers = new GeoHammers("геологические молотки");
        IceCrushers iceCrushers = new IceCrushers("ледорубы");
        Rocket rocket = new Rocket("ракета");

        // creating other objects
        Air air = new Air("Воздух");
        Chair chair = new Chair("кресло");
        Cave cave = new Cave("пещеру");
        Dots dots = new Dots("едва заметные точки");
        Grotto grotto = new Grotto("сосульчатый грот");
        Planet.Earth earth = new Planet.Earth("Земля");
        Planet.Moon moon = new Planet.Moon("Луна");
        Sun sun = new Sun("Солнце");
        Tunnel tunnel = new Tunnel("наклонному ледяному тоннелю");

        // action
        lunarians.setName("нееловцев");
        lunarians.spreadNews(astronauts, SimpleAction.GoingToFly, HowToAct.FAST);
        System.out.print(", и ");
        lunarians.setName("они");
        astronauts.setName("своими друзьями");
        lunarians.gatherToSayGoodbye(astronauts);
        System.out.print(".\n");
        lunarians.setName("Нееловцы");
        lunarians.cry(Emotion.HAPPINESS);
        System.out.print(".\n");
        lunarians.setName("Они");
        znaika.setName("Знайку");
        lunarians.kissGoodbye(znaika);
        System.out.print(".\nА ");
        kozlik.beEmotional(Emotion.HAPPINESS);
        System.out.print(", так как ");
        vintikAndShpuntik.giveRover(kozlik);
        System.out.print(".\nКак только ");
        neznaika.rememberSun();
        System.out.print(", ");
        neznaika.cry();
        System.out.print(".\n");
        neznaika.loseConsciousness();
        System.out.print(".\n");
        doctor.simpleAct(SimpleAction.Run);
        System.out.print(" и");
        neznaika.setName("Незнайки");
        doctor.giveSbAmmonia(neznaika);
        System.out.print(".\n");
        neznaika.setName("Незнайка");
        neznaika.comeToSenses();
        System.out.print(", но ");
        neznaika.bePale();
        System.out.print(".\nКак только ");
        chair.bePrepared();
        System.out.print(", ");
        znaika.giveCommandSuitsOn(new spacesuitOnCommand(astronauts, box));
        astronauts.addAstronaut(neznaika);
        neznaika.setName("Незнайку");
        System.out.print(", а ");
        kantikAndKvantik.putSuitOnSb(neznaika, box);
        System.out.print(".\n");
        neznaika.getSuit().getProperties();
        System.out.print(".\nЭтот ");
        neznaika.getSuit().prop.canLift();
        System.out.print(".\nКак только ");
        astronauts.checkSuits();
        System.out.print(", ");
        znaika.giveCommandTieToCord(new tieToCordCommand(astronauts));
        System.out.print("\nВ то же время ");
        kantikAndKvantik.tieSbToCord(neznaika, chair);
        System.out.print(".\n");
        znaika.checkPreparations(astronauts);
        System.out.print(".\n");
        astronauts.setName("Космонавты");
        astronauts.attachSth(alpenstocks, iceCrushers, geoHammers);
        System.out.print("и ");
        astronauts.lineInAChain();
        System.out.print(".\n");
        znaika.setName("Знайка");
        znaika.turnEngineOn(new turnEngineOnCommand(znaika.getSuit().engine));
        System.out.print(", и ");
        znaika.getSuit().prop.makeNoise();
        System.out.print(".\n");
        znaika.riseUp();
        System.out.print(" и ");
        znaika.setName("");
        znaika.takeOthersWith();
        System.out.print(".\n");
        lunarians.setName("Лунатики");
        lunarians.gasp(Emotion.AMAZEMENT);
        System.out.print(", увидев, как ");
        astronauts.setName("космонавты");
        astronauts.riseUpTogether();
        System.out.print(".\n");
        lunarians.setName("Все");
        lunarians.simpleAct(SimpleAction.Yell);
        System.out.print(",");
        lunarians.setName("");
        lunarians.simpleAct(SimpleAction.WaveHands);
        System.out.print(",");
        lunarians.simpleAct(SimpleAction.Applause);
        System.out.print(",");
        lunarians.simpleAct(SimpleAction.ThrowHats);
        System.out.print(".\n");
        lunarians.setName("Некоторые");
        lunarians.jump(Emotion.EXCITEMENT);
        System.out.print(" ");
        lunarians.setName("Многие");
        lunarians.simpleAct(SimpleAction.Cry);
        System.out.print(".\n");
        astronauts.setName("Космонавты");
        astronauts.riseUp(HowToAct.FASTER);
        System.out.print(".\nСкоро ");
        astronauts.setName("они");
        astronauts.turnInto(dots);
        System.out.print(" и наконец ");
        astronauts.setName("");
        astronauts.simpleAct(SimpleAction.BeOutOfSight, HowToAct.ATALL);
        System.out.print(".\n");
        astronauts.setName("пришельцы с далекой планеты Земли");
        lunarians.setName("Лунатики");
        lunarians.simpleAct(SimpleAction.Hope);
        System.out.print(", что ");
        astronauts.simpleAct(SimpleAction.Return, HowToAct.YET);
        System.out.print(" и ");
        astronauts.setName("их");
        lunarians.seeSb(astronauts, HowToAct.AGAIN);
        System.out.print(".\n");
        Hours.setTime(1);
        Hours.setTime(2);
        Hours.setTime(3);
        System.out.print("\n");
        astronauts.setName("своих друзей");
        lunarians.setName("Лунные коротышки");
        lunarians.lostHopeToSeeSb(astronauts, Time.SIMPLE, HowToAct.AGAIN);
        System.out.print(".\nНо ");
        lunarians.haveSthToWait(astronauts);
        System.out.print(".\n");
        astronauts.setName("Космонавты");
        astronauts.getThrough(tunnel, Time.ATTHATTIME, HowToAct.ALREADY);
        System.out.print(".\n");
        air.wasThin();
        System.out.print(", поэтому ");
        znaika.getSuit().prop.createThrust(ThrustQuality.WEAK);
        System.out.print(".\n");
        iceCrushers.setName("ледорубами");
        astronauts.arm(iceCrushers);
        System.out.print(", ");
        astronauts.overcome(IfManaged.MANAGED);
        System.out.print(" и");
        astronauts.setName("");
        astronauts.getTo(IfManaged.MANAGED, grotto);
        System.out.print(", а оттуда");
        astronauts.getTo(IfManaged.MANAGED, cave);
        System.out.print(",");
        cave.hasExit(moon);
        System.out.print(".\nЗдесь ");
        znaika.setName("Знайка");
        znaika.decidedToDivide();
        System.out.print(".\nВедь с тех пор, как ");
        rocket.landOnPlanet(new Planet.Moon("Луны"));
        System.out.print(", прошло много времени, и ");
        rocket.canBeBroken();
        System.out.print(", не говоря уже о том, что ");
        astronauts.mustCheckMechanisms();
        System.out.print(".\n");
        znaika.setName("себя");
        Astronauts group = znaika.makeNewGroup("первую группу", znaika, professor, fuksia, seledochka);
        System.out.print(".\n");
        znaika.giveCommandMine(new mineCrystalsCommand(astronauts));
        System.out.print(".\n");
        neznaika.setName("Незнайка");
        doctor.saySbFeelsBad(neznaika);
        System.out.print(".\n");
        znaika.setName("Знайка");
        znaika.giveCommandStayHere(new stayHereCommand(astronauts));
        System.out.print(" и ");
        znaika.setName("");
        znaika.goBackWith(group);
        System.out.print(".\n");
        Human.someoneImagines();
        System.out.print(", что ");
        moon.setName("Луне");
        moon.beDarkAtNight();
        System.out.print(", но это не так.\n");
        earth.setName("Землю");
        System.out.print("Так же, как ");
        moon.lightPlanet(earth);
        System.out.print(", ");
        earth.setName("Земля");
        moon.setName("Луну");
        earth.lightPlanet(moon);
        System.out.print(".\n");
        moon.setName("Луны");
        earth.reflectLight(moon);
        System.out.print(".\nЕсли ");
        moon.setName("Луна");
        earth.setName("Земли");
        earth.seemedFrom(moon);
        System.out.print(", то ");
        moon.setName("Луны");
        earth.setName("Земля");
        moon.seemedFrom(earth);
        System.out.print(".\n");
        group.setName("Знайка и его спутники");
        group.seeSky(Color.Black);
        System.out.print(" и");
        group.setName("");
        group.seeDisk(Color.LightBlue);
        System.out.print(".\nНа этот раз ");
        earth.seenAs(true);
        System.out.print(", так как ");
        earth.setName("Землю");
        sun.lightDirectly(earth);
        System.out.print(".\n");
        moon.beColorful(Color.Red, Color.Emerald);
        System.out.print(".\nЭто объяснялось тем, что ");
        moon.hasLuminousSurface();
        System.out.print(".\n");
        group.setName("космонавты");
        group.watchTwoColors(Color.Red, Color.Green);
        System.out.print(", и только ");
        rocket.illuminate(Color.Blue);
        System.out.print(".\n");
        geoHammers.setName("Геологические молотки");
        geoHammers.bangOnTheRocks();
        System.out.print(", так как ");
        ObjectInfo.getSecretInfo();
        System.out.print(".");

    }
    }